apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-traefik-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: {{ .Values.ingress.hostname }}
  secretName: traefik-cert
  dnsNames:
    - {{ .Values.ingress.hostname }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.ingress.clasteIssuareName }}