apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.stable.port }}
      targetPort: {{ .Values.stable.port }}